### ISSUE TITLE
Unable to  scan all the connected devices 

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#28]

**Comment by fakhrul-omar** [comment]
Even when setting scan timeout to a large value (1 minute), device(s) that exists on network still doesn't show up in list, compared to Yabe which can show them. This is due to config-tool-v3 that only puts device into list after receiving ReadPropertyMultiple ACK for device name and APDU timeout, even though it has received Who-Is reply.

Current scan sequence now is changed to listing any I-Am reply for Who-Is request and only later request for more details from selected device DDC after user pressed OK. DDC with unreplied details request after predefined timeout (5 seconds) will be dropped/ignored; popup info here.

**Comment by fakhrul-omar** [comment]
Scan button now can be pressed and depressed, signalling scan start/stop period. Since it still depends on DDC name to determine ADF DDC types (IP or MS/TP), when config-tool-v3 doesn't get name/timeout reply within 5 seconds, it'll continue connecting to DDC but as generic device. User then should either choose whether to continue connecting or reconnect through "Connect to device" dialog box once again.

**Comment by kslee911** [comment]
Tested ok, scan & connect improved as described.
