### ISSUE TITLE
Disable the update color 

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#29]
@fakhrul-omar , the update color is confusing.

**Comment by fakhrul-omar** [comment]
Didn't expect updating the cell colour will slow down updating/reading process from device, unless you mean it's user's reading process that's being slowed down, meaning it's hard for user to read the text/value. In latter case, should I disable altogether this update marker?

**Comment by mcchai** [comment]
The update marker is confusing because the color change is random

**Comment by fakhrul-omar** [comment]
Well, it's kinda random since sometimes config-tool doesn't get reply from device, being the trigger for the colour change, plus update is done in batches (i.e. 5 item for single update). In that case the cell colour will be out-of-order (doesn't match nearby cells), which user would perceive as random colour.

OK then, I'll disable update colour.
