### ISSUE TITLE
Modification to the variable tab

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#30]
@fakhrul-omar , can we combine the AV, BV & PT tab and view 1 tab at a time?

**Comment by fakhrul-omar** [comment]
Isn't that AV and BV have their own list/area, not in tabs? If you want to combine AV and BV in a single area like config-tool-v2, yup we can. It's just I thought that since we can have a lot of AVs and BVs, user will need to do scrolling a lot.

As for the PT, it's technically AI; I put them in unique area to follow config-tool-v2 interface. Though I'm considering to put that to AI list as well since we'll have LAV, PIV and IV lists later in same row as AV and BV.

**Comment by mcchai** [comment]
The current variable tab also has many scrolling to be done. The interface like config tool-v2 is simpler.

**Comment by fakhrul-omar** [comment]
Ermm, meaning it's better to put AV/BV, outputs and inputs in their own tabs like config-tool-v2? Well, we can do that. I thought that it's easier for user to look when all variables are in a single tab/place. Btw, since this is a big change, I need your confirmation first on how actually it'll be arranged.

**Comment by mcchai** [comment]
@fakhrul-omar , I will close the issue now. Thank you.
