### ISSUE TITLE
Object properties update issue

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#31]
@fakhrul-omar , the update of the properties are slow and inaccurate.

**Comment by fakhrul-omar** [comment]
Does slow means when user sets a value to any object properties, the change only gets reflected on the device after a while? Now that's weird, for whenever user writes/changes any value the update to device will be performed straight away. I'll need example for this.

If inaccurate means when user sets something -> the value changed back to previous value -> changed again to new value, then it's should be due to this: When user sets something (write) right after periodic refresh is performed (read), then the read will only give old value; user need to wait for next refresh to get new value. The intention is since user is the one that sets the value, they should already know what that value supposed to be anyway. I can send read request right after write, like Yabe is doing, to force refresh for that particular value. Should I?

**Comment by mcchai** [comment]
Yes, force refresh is better, if not, the user might perceive the changes made did not take place

**Comment by fakhrul-omar** [comment]
OK then.

**Comment by kslee911** [comment]
Current AV value = 0
Write AV value = 45

I still see the value jumps from 0 -> 45 -> 0. As @fakhrul-omar said already implemented but some error occurs and it's possibly being reverted. I'll move this to in progress until the fix is confirmed.
