### ISSUE TITLE
DDC Connection Lost

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#36]

**Comment by fakhrul-omar** [comment]
Isn't this the same as #26? If the lost is due to actual problem (DDC doesn't give reply within timeout period), then it's fine. But if config-tool keeps disconnecting itself, then it's a bug. Not sure which one.

**Comment by mcchai** [comment]
Yes, its the same issue. What causes the bug?

**Comment by fakhrul-omar** [comment]
Don't know, I can't replicate that. Sometimes when I connect to MS/TP device it doesn't give reply to any request, so perhaps it's timeout. If that's really the case, then I can't do anything on my side; I'll ask hardware side for this later.

Since it's the same/duplicate as #26, I suggest to close this one.
