### ISSUE TITLE
Variables cannot be added into the IF-ELSE logic

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#48]
@fakhrul-omar 

![controls block cannot add block](https://user-images.githubusercontent.com/38911466/46568867-ca2fe980-c97e-11e8-9c27-951bcd602106.jpg)
![controls block doesnt take changes](https://user-images.githubusercontent.com/38911466/46568869-cac88000-c97e-11e8-8eac-7cec4d1b7f5f.jpg)

**Comment by fakhrul-omar** [comment]
Value block type (dictated by its shape) needs to match placeholder (destination). From the images, looks like the placeholder type is set to boolean while value block is NULL.

**Comment by wslow-adft** [comment]
@thyong-adft @mcchai  Ready for test. The IF_ELSE block only able to drag the Statement block rather than variable block, but config tool should not able to let user change the setting in the world.(https://user-images.githubusercontent.com/38911466/46568869-cac88000-c97e-11e8-8eac-7cec4d1b7f5f.jpg)
So config tool had disable for setting the variable block in the IF_ELSE statement block.

**Comment by mcchai** [comment]
Yes,the statement block can be dragged into the IF_ELSE block.
