### ISSUE TITLE
Alarm event does not take place although the alarm source is triggered.

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#49]
@fakhrul-omar 

The alarm source was added. However, when the IP device is reopen, the alarm source disappeared. Also the alarm event does not take place although the alarm source is triggered. 

![alarm no event](https://user-images.githubusercontent.com/38911466/46568898-432f4100-c97f-11e8-9ad6-5c355e49189e.jpg)
![alarm source gone after reconnect](https://user-images.githubusercontent.com/38911466/46568899-432f4100-c97f-11e8-9542-ad43e7b3700a.jpg)

**Comment by fakhrul-omar** [comment]
For the disappearance problem, user needs to right-click in "Alarm source" listbox and select "Refresh list (all group)". After that, try selecting item in "Alarm group" listbox again.

For missing event, try confirm whether item in "Notification recipient" list box has its details, particularly port number, matches what is currently being used by config-tool-v3. This is because when the last device at particular network interface (based on its IP address) is closed/disconnected, it'll close current port and use a random port next time it connects to the device.

**Comment by wslow-adft** [comment]
@thyong-adft @mcchai Ready for test. The port number of config tool is random assign and it will be change when every time connect to device, so the alarm event will not forward the alarm message to the correct port.
So, a check box is added. If the checkbox had been checked, then the it will forward the message to current port, but user need to do it manually every time they need connect to device because the device can't store the checkbox status.
![image](https://user-images.githubusercontent.com/38875038/47056407-cd34a080-d1ee-11e8-96f7-e2127d63cad6.png)

**Comment by mcchai** [comment]
![alarm group crash](https://user-images.githubusercontent.com/38911466/47254287-1ad13780-d493-11e8-8f78-cac2167a66cf.jpg)
The config tool crashed after the "Select destination now" is clicked

**Comment by mcchai** [comment]
@wslow-adft , I will close the issue now. Thank you.
